### ISSUE TITLE
Failed to log in to Serializd

### ISSUE THREAD

**Issue by Addy-21** [Velocidensity/trakt-to-serializd#1]
It shows: "ERROR    Failed to log in to Serializd using provided credentials!" after entering email and password although both entries are correct.

**Comment by Velocidensity** [comment]
Fixed in https://github.com/Velocidensity/serializd-py/commit/7c59673c110b0a7d0d308476ddc771c29503ed4c (https://github.com/Velocidensity/trakt-to-serializd/commit/6f801c3b6c4dfc0a2562f58918dab140130df1ef).

You will need to update the serializd-py dependency, running the pip command with `-U` added should do it, or `poetry update` if you're using poetry.
